### ISSUE TITLE
Server absturtz beim erkunden ! 

### ISSUE THREAD

**Issue by sonykill** [ToadsworthLP/GronkhsLitW#4]
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 6/23/16 8:25 PM
Description: Exception in server tick loop

java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at farseek.core.ReplacedMethod.apply(MethodReplacementTransformer.scala:114)
	at farseek.world.gen.ChunkGeneratorExtensions$.generateWorld(ChunkGeneratorExtensions.scala:17)
	at farseek.world.gen.ChunkGeneratorExtensions.generateWorld(ChunkGeneratorExtensions.scala)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: net.minecraft.util.ReportedException: Exception getting block type in world
	at net.minecraft.world.World.func_147439_a(World.java:354)
	at plantmegapack.worldgen.PMPGenBase.isAdjacentToBlockMaterial(PMPGenBase.java:355)
	at plantmegapack.worldgen.PMPSpawnLocation.getSpawnLocationData(PMPSpawnLocation.java:103)
	at plantmegapack.worldgen.PMPWorldGenerator.generateSurface(PMPWorldGenerator.java:80)
	at plantmegapack.worldgen.PMPWorldGenerator.generate(PMPWorldGenerator.java:42)
	at cpw.mods.fml.common.registry.GameRegistry.farseek_core_FarseekClassTransformer_cpw_mods_fml_common_registry_GameRegistry_generateWorld(GameRegistry.java:112)
	... 19 more
Caused by: java.lang.NullPointerException
	at farseek.block.package$$anonfun$naturalStoneBlocks$1.apply(package.scala:63)
	at farseek.block.package$$anonfun$naturalStoneBlocks$1.apply(package.scala:63)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
	at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:186)
	at farseek.block.package$.dictionaryBlocksAndData(package.scala:72)
	at farseek.block.package$.dictionaryBlocks(package.scala:68)
	at farseek.block.package$.naturalStoneBlocks$lzycompute(package.scala:63)
	at farseek.block.package$.naturalStoneBlocks(package.scala:64)
	at farseek.block.package$BlockValue$.isNaturalStone$extension(package.scala:83)
	at farseek.block.package$BlockValue$.isGround$extension(package.scala)
	at streams.world.gen.structure.RiverComponent$$anonfun$build$2$$anonfun$apply$3.apply(RiverComponent.scala:275)
	at streams.world.gen.structure.RiverComponent$$anonfun$build$2$$anonfun$apply$3.apply(RiverComponent.scala:274)
	at scala.collection.TraversableViewLike$TakenWhile$$anonfun$foreach$5.apply(TraversableViewLike.scala:207)
	at scala.collection.TraversableViewLike$Mapped$$anonfun$foreach$2.apply(TraversableViewLike.scala:169)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.SeqLike$$anon$2.foreach(SeqLike.scala:638)
	at scala.collection.TraversableViewLike$Mapped$class.foreach(TraversableViewLike.scala:168)
	at scala.collection.SeqViewLike$$anon$3.foreach(SeqViewLike.scala:186)
	at scala.collection.TraversableViewLike$TakenWhile$class.foreach(TraversableViewLike.scala:205)
	at scala.collection.SeqViewLike$$anon$8.foreach(SeqViewLike.scala:191)
	at streams.world.gen.structure.RiverComponent$$anonfun$build$2.apply(RiverComponent.scala:274)
	at streams.world.gen.structure.RiverComponent$$anonfun$build$2.apply(RiverComponent.scala:265)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
	at streams.world.gen.structure.RiverComponent.build(RiverComponent.scala:265)
	at farseek.world.gen.structure.StructureComponent.build(StructureComponent.scala:19)
	at farseek.world.gen.structure.Structure$$anonfun$build$2.apply(Structure.scala:37)
	at farseek.world.gen.structure.Structure$$anonfun$build$2.apply(Structure.scala:37)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at farseek.world.gen.structure.Structure.build(Structure.scala:37)
	at streams.world.gen.structure.RiverGenerator$$anonfun$build$1$$anonfun$apply$3$$anonfun$apply$4.apply(RiverGenerator.scala:61)
	at streams.world.gen.structure.RiverGenerator$$anonfun$build$1$$anonfun$apply$3$$anonfun$apply$4.apply(RiverGenerator.scala:61)
	at scala.Option.foreach(Option.scala:245)
	at streams.world.gen.structure.RiverGenerator$$anonfun$build$1$$anonfun$apply$3.apply(RiverGenerator.scala:61)
	at streams.world.gen.structure.RiverGenerator$$anonfun$build$1$$anonfun$apply$3.apply(RiverGenerator.scala:61)
	at scala.Option.foreach(Option.scala:245)
	at streams.world.gen.structure.RiverGenerator$$anonfun$build$1.apply(RiverGenerator.scala:61)
	at streams.world.gen.structure.RiverGenerator$$anonfun$build$1.apply(RiverGenerator.scala:60)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:83)
	at streams.world.gen.structure.RiverGenerator.build(RiverGenerator.scala:60)
	at farseek.world.gen.structure.StructureGenerator.onPrePopulateChunk(StructureGenerator.scala:75)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_271_StructureGenerator_onPrePopulateChunk_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:377)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.13.0-24-generic
	Java Version: 1.7.0_91, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1243590328 bytes (1185 MB) / 3113943040 bytes (2969 MB) up to 4151836672 bytes (3959 MB)
	JVM Flags: 9 total; -Xms3G -Xmx4G -XX:PermSize=256m -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 15, tcache: 93, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (GronkhsLifeInTheWoods.jar) 
	UCHIJAAAA	Forge{10.13.4.1492} [Minecraft Forge] (GronkhsLifeInTheWoods.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	koresample{1.7.10-1.3.0} [Kore Sample] (KoreSample-1.7.10-1.3.0.jar) 
	UCHIJAAAA	dendrology{1.7.10-1.3.0} [Ancient Trees] (AncientTrees-1.7.10-1.3.0.jar) 
	UCHIJAAAA	animalsPlus{1.2} [Animals+] (animalsPlus-1.2.jar) 
	UCHIJAAAA	antiqueatlas{4.2.2-1.7.10} [Antique Atlas] (antiqueatlas-4.2.2-1.7.10.jar) 
	UCHIJAAAA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHIJAAAA	AutoSapling{1.0} [AutoSapling] (AutoSapling-1.1.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1338-universal.jar) 
	UCHIJAAAA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJAAAA	ExtrabiomesXL{3.16.2} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.2.jar) 
	UCHIJAAAA	BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition] (BiblioWoods[ExtraBiomesXL][v1.4].jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.16} [BuildCraft] (buildcraft-7.1.16-core.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.16} [BC Builders] (buildcraft-7.1.16-builders.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.16} [BC Energy] (buildcraft-7.1.16-energy.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.16} [BC Factory] (buildcraft-7.1.16-factory.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.16} [BC Robotics] (buildcraft-7.1.16-robotics.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.16} [BC Silicon] (buildcraft-7.1.16-silicon.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.16} [BC Transport] (buildcraft-7.1.16-transport.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.4} [BuildCraft Compat] (buildcraft-compat-7.1.4.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) 
	UCHIJAAAA	ChiselFacades{1.7.10-2.11-cricket} [Chisel Facades] (ChiselFacades-1.7.10-2.11-cricket.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.2_1.7.10.jar) 
	UCHIJAAAA	props{2.3.2} [Decocraft] (Decocraft-2.3.2_1.7.10.jar) 
	UCHIJAAAA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UCHIJAAAA	DimensionalAnchors{59.0.3} [Dimensional Anchors] (dimensional-anchor-59.0.3.jar) 
	UCHIJAAAA	EasyCrafting{1.7.10-2.0.1.16} [Easy Crafting] (EasyCrafting-1.7.10-2.0.1.16.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	extrabuttons{1.7.10.1} [ExtraButtons] (ExtraButtons-1.7.10.1.jar) 
	UCHIJAAAA	farseek{1.0.1} [Farseek] (Farseek-1.0.1.jar) 
	UCHIJAAAA	GardenCore{1.7.10-1.6.3} [Garden Core] (GardenStuff-1.7.10-1.6.3.jar) 
	UCHIJAAAA	GardenContainers{1.7.10-1.6.3} [Garden Containers] (GardenStuff-1.7.10-1.6.3.jar) 
	UCHIJAAAA	GardenStuff{1.7.10-1.6.3} [Garden Stuff] (GardenStuff-1.7.10-1.6.3.jar) 
	UCHIJAAAA	GardenTrees{1.7.10-1.6.3} [Garden Trees] (GardenStuff-1.7.10-1.6.3.jar) 
	UCHIJAAAA	gravestonemod{1.7.2} [GraveStone] (GraveStones-1.7.2_1.4.jar) 
	UCHIJAAAA	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) 
	UCHIJAAAA	litwr{1.7.10-1.0.7} [Life in the Woods: Renaissance] (LitWR-1.7.10-1.0.7.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	Mystcraft{0.12.3.02} [Mystcraft] (mystcraft-1.7.10-0.12.3.02.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10j.jar) 
	UCHIJAAAA	plantmegapack{4.23} [Plant Mega Pack] (plantmegapack-4.23-1.7.10-1448.jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJAAAA	AS_Ruins{15.4} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJAAAA	simplerefinement{1.0} [Simple Refinement] (SimpleRefinement-mc1.7.10-1.0 (1).jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.5.6} [Storage Drawers] (StorageDrawers-1.7.10-1.5.6.jar) 
	UCHIJAAAA	StorageDrawersBop{1.7.10-1.0.1} [Storage Drawers: Biomes O' Plenty Pack] (StorageDrawers-BiomesOPlenty-1.7.10-1.0.1.jar) 
	UCHIJAAAA	streams{0.1.2} [Streams] (Streams-0.1.2.jar) 
	UCHIJAAAA	UndergroundBiomes{0.7} [Underground Biomes Constructs] (UndergroundBiomesConstructs-1.7.2-0.7.jar) 
	UCHIJAAAA	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
	UCHIJAAAA	MSC2{1.2.1} [Mob Spawn Controls 2] (MSC2.jar) 
	UCHIJAAAA	VeganOption{0.1.1} [The Vegan Option] (VeganOption-mc1.7.10-0.1.1.jar) 
	CoFHCore: -[1.7.10]3.1.2-325
	NetherOres: -[1.7.10]2.3.1-22
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 4 / 20; [EntityPlayerMP['NessyZu'/6968, l='world', x=2402.82, y=85.00, z=-1759.77], EntityPlayerMP['Kendalor'/1282, l='world', x=365.00, y=117.00, z=-346.36], EntityPlayerMP['Knallberto'/104759, l='world', x=2486.05, y=28.00, z=-1671.54], EntityPlayerMP['HeadyXx'/183, l='world', x=-5286.48, y=67.00, z=2079.34]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by ToadsworthLP** [comment]
Das ist ein relativ bekanntes Problem mit dem Streams-Mod (Die Mod, die Flüsse verbessert) bzw. einer Library namens Farseek. Ich werde mal nachsehen, ob in der Zwischenzeit schon ein Update dafür draußen ist. Wenn ja, dann werde ich das Pack demnächst updaten.
