### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by scamille** [ToadsworthLP/GronkhsLitW#65]
LITW crasht im LAN Modus einige Minuten nachdem jemand den Server joint. SinglePlayer geht alles gut.

- Gronks Life in the Woods Version 3.4
- Windows 10 x64 host system, i5 Kabylake
- Shader: Internal
- java version "1.8.0_131" / Java(TM) SE Runtime Environment (build 1.8.0_131-b11) / Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

```
[08:54:16] [Client thread/ERROR]: Couldn't render entity
java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374) ~[bmh.class:?]
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364) ~[bmh.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:9276) ~[blm.class:?]
	at ItemRendererOF.func_78443_a(ItemRendererOF.java:102) ~[ItemRendererOF.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_77029_c(RenderPlayer.java:398) ~[bop.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_77029_c(RenderPlayer.java:496) ~[bop.class:?]
	at RenderPlayerOF.func_77029_c(RenderPlayerOF.java:31) ~[RenderPlayerOF.class:?]
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:213) [boh.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158) [bop.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521) [bop.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293) [bnn.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271) [bnn.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244) [bnn.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:716) [bma.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1596) [blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1334) [blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[08:54:19] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:339) ~[bnn.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271) ~[bnn.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244) ~[bnn.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:716) ~[bma.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1596) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1334) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374) ~[bmh.class:?]
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364) ~[bmh.class:?]
	at net.minecraft.client.renderer.entity.Render.func_147906_a(SourceFile:349) ~[bno.class:?]
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_96449_a(RendererLivingEntity.java:495) ~[boh.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_96449_a(RenderPlayer.java:436) ~[bop.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_96449_a(RenderPlayer.java:476) ~[bop.class:?]
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_77033_b(RendererLivingEntity.java:475) ~[boh.class:?]
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:280) ~[boh.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158) ~[bop.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521) ~[bop.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293) ~[bnn.class:?]
	... 14 more
[08:54:19] [Server thread/INFO]: Stopping server
```

**Comment by scamille** [comment]
Habe den Tipp bekommen Chunk Loading von Smooth auf Default zu setzen. Ich beobachte mal ob dies das Problem behebt.

**Comment by ToadsworthLP** [comment]
Wenn das nicht funktioniert, dann versuche mal mit den Serverdateien einen lokalen Server aufzusetzten, das ist meistens stabiler

**Comment by scamille** [comment]
Scheint jetzt stabil zu sein, Danke.
